from pathlib import Path
import re,json,hashlib
root=Path('/workspace/scratch/bcf004da8655/ever-deeper')
removed={}
def read(p): return (root/p).read_text()
def save(p,s): (root/p).write_text(s)
def funcs(p,names):
 s=read(p)
 for name in names:
  s,n=re.subn(r'^func '+re.escape(name)+r'\([\s\S]*?(?=^func |\Z)','',s,count=1,flags=re.M)
  assert n==1,(p,name)
 removed[p]=names
 save(p,s)
def rep(s,a,b='',count=None):
 assert a in s,a[:150]
 if count is not None: assert s.count(a)==count,(s.count(a),a)
 return s.replace(a,b)
def drop_lines(s,needles):
 return ''.join(line for line in s.splitlines(True) if not any(x in line for x in needles))
def cut(s,start,end):
 a=s.index(start); b=s.index(end,a); return s[:a]+s[b:]
p='scripts/state/run_state.gd'
funcs(p,['storage_chest_cost','storage_chest_type_count','buy_storage_chest','nearby_storage_chests','auto_sort_resources','take_all_from_storage','is_surface_chest_opened','open_surface_chest','open_mossvein_chest','pending_chest_reward_loot','collect_chest_loot','_new_storage_chest','_storage_type_count','_default_opened_chests','_all_chest_ids'])
s=read(p)
s=drop_lines(s,['const AUTO_SORT_RADIUS:','const STORAGE_CHEST_CAPACITY:','var opened_chests:','var pending_chest_loot:','opened_chests = _default_opened_chests()','pending_chest_loot = {}','"opened_chests": opened_chests','"pending_chest_loot": pending_chest_loot','"auto_sort_radius": AUTO_SORT_RADIUS','"storage_type_capacity": STORAGE_CHEST_CAPACITY','"storage": {"gold": storage_chest_cost()}'])
s=rep(s,'\t\t"storage":\n\t\t\treturn {"gold": storage_chest_cost()}\n')
s=rep(s,'["wall", "lamp", "storage"]','["wall", "lamp"]')
s=rep(s,'\tif kind in ["wall", "lamp"]:\n\t\tvar tiles: Array = Array(hub.get("tiles", [])).duplicate(true)\n\t\ttiles.append({"col": col, "row": row, "kind": kind})\n\t\thub["tiles"] = tiles\n\telse:\n\t\tvar chest: = _new_storage_chest("hub", 1, hub_cell_center(col, row), false)\n\t\tvar chests: Array = Array(base.get("chests", [])).duplicate(true)\n\t\tchests.append(chest)\n\t\tbase["chests"] = chests\n\t\tresult["module"] = chest.duplicate(true)\n','\tvar tiles: Array = Array(hub.get("tiles", [])).duplicate(true)\n\ttiles.append({"col": col, "row": row, "kind": kind})\n\thub["tiles"] = tiles\n')
s=cut(s,'\topened_chests = _sanitize_bool_map(','\tdrill_goal_scene = _sanitize_allowed_id(')
s=cut(s,'\t\t"chests": [{','\t}\n\n\nfunc _sanitize_hub_state')
s=cut(s,'\tvar raw_chests: Variant = source.get("chests", [])','\treturn result\n\n\nfunc _sanitize_base_module')
s=rep(s,'\tfor chest_value in Array(base.get("chests", [])):\n\t\tif chest_value is Dictionary:\n\t\t\tresult.append(chest_value)\n')
s=cut(s,'\tvar chests: Array = Array(base.get("chests", [])).duplicate(true)','\n\nfunc _module_is_at_location')
save(p,s)
p='scripts/progression/mossvein_progression.gd'
funcs(p,['surface_chest_ids','surface_chest_claim_plan'])
s=read(p);s=drop_lines(s,['var _surface_chest_index:'])
s=cut(s,'\tfor chest_value in Array(_source.CHEST_DEFINITIONS):','\n\nfunc _normalized_reward_store')
s=rep(s,'"STARFORGE_VARIANTS", "CHEST_DEFINITIONS",','"STARFORGE_VARIANTS",')
save(p,s)
p='scripts/world/world_catalog.gd'
funcs(p,['_chests_for_world'])
s=read(p);s=re.sub(r'^const CHEST_ASSETS: = \{[\s\S]*?^}\n\n','',s,count=1,flags=re.M)
s=drop_lines(s,['var chests: = _chests_for_world(world_id)','"chests": chests'])
s=rep(s,'"MINE_DISCOVERY_PROFILES", "PICKAXES", "STATIONS", "CHEST_DEFINITIONS",','"MINE_DISCOVERY_PROFILES", "PICKAXES", "STATIONS",')
save(p,s)
p='scripts/world/surface_world.gd'
funcs(p,['_build_surface_chests','_refresh_surface_chest_visuals','_refresh_surface_storage_nodes','_surface_chest_requirement_met','_sync_pending_chest_loot_drops','_visible_chest_drop_amount','_spawn_chest_loot_reward','_spawn_chest_loot_piece','_update_chest_loot_drops','_nearest_unopened_surface_chest','_nearest_surface_storage','surface_chest_position'])
s=read(p);s=re.sub(r'^const SURFACE_CHEST_TEXTURES: = \{[\s\S]*?^}\n\n','',s,count=1,flags=re.M)
s=drop_lines(s,['const CHEST_INTERACT_RADIUS:','const CHEST_DROP_PICKUP_RADIUS:','const STORAGE_CHEST:','var surface_chest_nodes:','var surface_storage_nodes:','var chest_loot_drops:','var chest_visual_state:','var storage_visual_signature:','var chest_loot_signature:','\t_build_surface_chests()','\t_refresh_surface_storage_nodes()','\t_update_chest_loot_drops(safe_delta)','\tchest_visual_state.clear()','\tstorage_visual_signature = ""','\t_refresh_surface_chest_visuals()','\t_sync_pending_chest_loot_drops()','\t\t"chest": return chest_loot_drops[index]'])
s=rep(s,'\tfor drop in chest_loot_drops:\n\t\tvar chest_drop_sprite: Sprite2D = drop.get("sprite")\n\t\tif is_instance_valid(chest_drop_sprite):\n\t\t\tchest_drop_sprite.queue_free()\n\tchest_loot_drops.clear()\n\tchest_loot_signature = ""\n')
s=cut(s,'\tfor index in range(chest_loot_drops.size()):','\treturn candidates\n')
s=rep(s,'\t\t"chest":\n\t\t\tif index < 0 or index >= chest_loot_drops.size():\n\t\t\t\treturn false\n\t\t\tdrop = chest_loot_drops[index]\n\t\t\tchest_loot_drops.remove_at(index)\n')
s=rep(s,'\tif bucket == "chest":\n\t\tvar collected: = RunState.collect_chest_loot(\n\t\t\tString(drop.get("chest_id", owner_id)),\n\t\t\tString(drop.get("reward_id", "")),\n\t\t\tamount\n\t\t)\n\t\tsurface_drop_budget_auto_collected += collected\n\telse:\n\t\tvar count_as_mined: = bucket in ["ore", "surface_mountain"]\n\t\tRunState.add_resource(String(drop.get("kind", "")), amount, count_as_mined)\n\t\tsurface_drop_budget_auto_collected += amount\n','\tvar count_as_mined: = bucket in ["ore", "surface_mountain"]\n\tRunState.add_resource(String(drop.get("kind", "")), amount, count_as_mined)\n\tsurface_drop_budget_auto_collected += amount\n')
s=cut(s,'\tvar storage_id: = _nearest_surface_storage(world_position)','\tif (\n\t\tnext_context.is_empty()')
s=cut(s,'\tvar chest_rows: Array[Dictionary] = []','\treturn {')
s=drop_lines(s,['"chests": chest_rows'])
save(p,s)
p='scripts/world/hub_world.gd'
funcs(p,['storage_cost','nearby_storage_modules','storage_type_count','_empty_resource_store'])
s=read(p);s=drop_lines(s,['const AUTO_SORT_RADIUS:','const STORAGE_TYPE_CAPACITY:','const STORAGE_TEXTURE:'])
s=rep(s,'"wall", "lamp", "storage", "forge", "sell",','"wall", "lamp", "forge", "sell",')
s=rep(s,'["wall", "lamp", "storage"]','["wall", "lamp"]')
s=cut(s,'\tvar chests: Array = Array(base_state.get("chests", []))','\tif changed_state:')
s=rep(s,'\t\t"storage":\n\t\t\treturn {"gold": storage_cost()}\n')
s=rep(s,'\tif kind in ["wall", "lamp"]:\n\t\tvar tiles: Array = Array(hub_state.get("tiles", []))\n\t\ttiles.append({"col": col, "row": row, "kind": kind})\n\t\thub_state["tiles"] = tiles\n','\tvar tiles: Array = Array(hub_state.get("tiles", []))\n\ttiles.append({"col": col, "row": row, "kind": kind})\n\thub_state["tiles"] = tiles\n')
s=cut(s,'\telse:\n\t\tvar next_id: = maxi(2, int(base_state.get("nextChestId", 2)))','\t_commit_transaction(transaction)')
s=rep(s,'\tfor chest_value in base_state.get("chests", []):\n\t\tresult.append(Dictionary(chest_value))\n')
s=cut(s,'\tvar chests: Array = Array(base_state.get("chests", []))','\n\nfunc _module_is_here')
s=rep(s,'\tif not result.has("chests"):\n\t\tresult["chests"] = []\n\tresult["nextChestId"] = maxi(2, int(result.get("nextChestId", Array(result.chests).size() + 1)))\n')
s=rep(s,'func _sanitize_base_state(source: Dictionary) -> Dictionary:\n\tvar result: = source.duplicate(true)','func _sanitize_base_state(source: Dictionary) -> Dictionary:\n\tvar result: Dictionary = {}\n\tfor module_id in ["forge", "sell"]:\n\t\tif source.get(module_id) is Dictionary:\n\t\t\tresult[module_id] = Dictionary(source[module_id]).duplicate(true)')
save(p,s)
p='scripts/main.gd'
funcs(p,['_auto_sort_inventory','_open_surface_chest','_use_surface_storage','_surface_chest_definition','_surface_chest_reward_label','_surface_chest_status','_surface_chest_is_ready'])
s=read(p);s=drop_lines(s,['resource_inventory.auto_sort_requested.connect(_auto_sort_inventory)'])
s=rep(s,'\tif context.begins_with("chest:"):\n\t\t_set_status(_surface_chest_status(context.trim_prefix("chest:")))\n\telif context.begins_with("gate:"):','\tif context.begins_with("gate:"):')
s=rep(s,'\tif surface_context.begins_with("chest:"):\n\t\t_open_surface_chest(surface_context.trim_prefix("chest:"))\n\t\treturn\n\tif surface_context.begins_with("storage:"):\n\t\t_use_surface_storage(surface_context.trim_prefix("storage:"))\n\t\treturn\n')
s=cut(s,'\t\t"storage":\n\t\t\tvar moved: = RunState.auto_sort_resources','\t_sync_hub_runtime()')
s=rep(s,'func _on_hub_module_activated(module_id: String, kind: String)','func _on_hub_module_activated(_module_id: String, kind: String)')
s=rep(s,'\t\tif surface_context.begins_with("chest:"):\n\t\t\tvar chest: = _surface_chest_definition(surface_context.trim_prefix("chest:"))\n\t\t\tenabled = not chest.is_empty() and _surface_chest_is_ready(chest)\n\t\t\tlabel = "OPEN" if enabled else "LOCKED"\n\t\telif surface_context.begins_with("storage:"):\n\t\t\tlabel = "USE"\n\t\telif surface_context.begins_with("enter:"):','\t\tif surface_context.begins_with("enter:"):')
s=rep(s,'\tif phase == "hub":\n\t\tvar stored: = 0\n\t\tfor module_value in RunState.all_base_modules():\n\t\t\tvar module: Dictionary = Dictionary(module_value)\n\t\t\tif String(module.get("kind", "")) != "storage":\n\t\t\t\tcontinue\n\t\t\tfor amount in Dictionary(module.get("items", {})).values():\n\t\t\t\tstored += int(amount)\n\t\treturn "POUCH %d  ·  STORAGE %d  ·  GOLD %d" % [RunState.cargo_count(), stored, RunState.gold]','\tif phase == "hub":\n\t\treturn "POUCH %d  ·  GOLD %d" % [RunState.cargo_count(), RunState.gold]')
s=rep(s,'Dictionary(RunState.protected_progress_cargo()),\n\t\tphase == "hub"','Dictionary(RunState.protected_progress_cargo())')
s=rep(s,'Dictionary(RunState.protected_progress_cargo()),\n\t\t\tphase == "hub"','Dictionary(RunState.protected_progress_cargo())')
save(p,s)
p='scripts/ui/resource_inventory.gd';s=read(p)
s=rep(s,', auto_sort_enabled: bool','')
s=rep(s,'_refresh(cargo, protected, auto_sort_enabled)','_refresh(cargo, protected)')
s=rep(s,'return close_button.custom_minimum_size.y >= minimum_height and auto_sort_button.custom_minimum_size.y >= minimum_height','return close_button.custom_minimum_size.y >= minimum_height')
s=drop_lines(s,['signal auto_sort_requested','var auto_sort_button:', 'auto_sort_button.', 'auto_sort_button =', 'summary_row.add_child(auto_sort_button)', '"auto_sort_height":'])
s=rep(s,'This material will not be sold or auto-sorted while your next upgrade needs it.','This material will not be sold while your next upgrade needs it.')
save(p,s)
p='scripts/qa/menu_touch_qa.gd';s=read(p);s=rep(s,'main.resource_inventory.open_inventory(cargo,{},false)','main.resource_inventory.open_inventory(cargo,{})');save(p,s)
p='scripts/progression/achievement_service.gd';s=read(p)
s=drop_lines(s,['"opened": _true_count(RunState.opened_chests)','var opened: = int(metrics.opened)','"treasure_found": return opened','"cache_hunter": return opened','"chestmaster": return opened'])
# Obsolete achievement records must not inflate progress after definitions disappear.
s=rep(s,'\t\tfor id in Dictionary(parsed).get("records", {}):\n\t\t\trecords[String(id)] = maxi(0, int(Dictionary(parsed).records[id]))','\t\tfor id in Dictionary(parsed).get("records", {}):\n\t\t\tif Dictionary(GameData.data.ACHIEVEMENT_BY_ID).has(String(id)):\n\t\t\t\trecords[String(id)] = maxi(0, int(Dictionary(parsed).records[id]))')
save(p,s)
Path('/tmp/ever-removed-functions.json').write_text(json.dumps(removed,indent=2))
print('Removed',sum(map(len,removed.values())),'chest functions and runtime/UI branches.')
