extends SceneTree

func _initialize() -> void:
	var recorder: Node = load("res://recorder.gd").new()
	root.add_child(recorder)
	assert(recorder.begin_span(1, 12, 11) == -1)
	assert(recorder.start_capture())
	assert(not recorder.start_capture())
	assert(recorder.export_capture().error == "export_while_active")
	var outer: int = recorder.begin_span(2, 13, 11, 12)
	var inner: int = recorder.begin_span(1, 13, 11, 12)
	recorder.end_span(inner, 13, 12)
	recorder.end_span(outer, 13, 12)
	var save: int = recorder.begin_span(3, 13, 12)
	recorder.end_span(save, 13, 12, 0, ERR_CANT_OPEN)
	assert(recorder.stop_capture())
	var capture: Dictionary = recorder.export_capture()
	assert(capture.count == 3 and capture.dropped == 0 and capture.integrity_errors == 0 and capture.open_parent == -1)
	assert(capture.rows[0][11] == -1 and capture.rows[1][11] == 0 and capture.rows[2][11] == -1)
	assert(capture.rows[0][1] <= capture.rows[1][1] and capture.rows[0][2] >= capture.rows[1][2])
	assert(capture.rows[2][10] == 0 and capture.rows[2][14] == ERR_CANT_OPEN)
	assert(recorder.start_capture())
	for index in recorder.CAPACITY + 2:
		var span: int = recorder.begin_span(3, 12, 11)
		recorder.end_span(span, 12, 11)
	assert(recorder.stop_capture())
	capture = recorder.export_capture()
	assert(capture.count == recorder.CAPACITY and capture.dropped == 2 and capture.integrity_errors == 0 and capture.open_parent == -1)
	assert(recorder.start_capture())
	outer = recorder.begin_span(2, 13, 11)
	inner = recorder.begin_span(1, 13, 11)
	recorder.end_span(outer, 13, 12)
	recorder.end_span(inner, 13, 12)
	recorder.end_span(outer, 13, 12)
	assert(recorder.stop_capture())
	assert(recorder.export_capture().integrity_errors == 1)
	recorder.free()
	print("HITCH_RECORDER_CHECKS_OK nested=1 overflow=2 integrity_guard=1")
	quit(0)
